### ISSUE TITLE
Copy/Paste error v2.

### ISSUE THREAD

**Issue by schroef** [nutti/Copy-And-Paste-UV#6] opened 2015-02-23 01:07 UTC
I cant seem to get it to work at a new model i just created. Im really doubting myself what im doing wrong have tried bot 2.73 & 2.72
In both of them there's seems to be a vertices indices issue. is it my work flow? i tried adding the one door to the other and use copy paste uv. Also tried seperate meshes and tried copy uv maps as well.

For example if i take a simple cube and copy this without changing it it works. But as soon as i change something by deleting a edge and make new faces it stops working. When the indices change it stops to work. Didnt this used to work however in earlier versions no matter the indices index?

EDIT
indeed it worked, just tried version 1.1 and when ive changed the cube the uv are copied perfect. Perhaps the new function 'sequence' changed it, i believe this does look at the indices index. Try this simple cube scene, with version 2.1 it wont copy/paste properly while with v1.1 it will

here 2 files; https://www.dropbox.com/s/ka1iyopqp0rco5r/vube%20test%20uv%20paste.blend?dl=0

https://www.dropbox.com/s/32bjknbvu1pqfqb/Window%20frame.blend?dl=0

**Comment by nutti** [comment] 2015-03-22 12:26
Thanks, for your report.

However I tried your operation with v1.1, same problem is occurred.
And it seems that indices sequence is not changed both v1.1 and v2.1.
So, please tell me your operation more detail.

**Comment by schroef** [comment] 2015-04-10 01:54
Well as i stated with a simple cube it does work, but with a more complex shape it doesnt work always correct. I dont know what i need to make more clear. I just take model and if i find a symmetry i than copy one side and paste it to the other side. This results most of the time in weird UV mapping.

Sometimes when the meshes are separate in a object i copy mirror the mesh to fix it. But when the mesh is one part like a wall or something else i cant fix it.

**Comment by nutti** [comment] 2015-04-12 12:12
I want to check your problem.

1. Copy/Paste is failed when operation is done in one mesh.
2. Copy/Paste is succeeded when operation is done between two different meshes (but these are same shape).

Is it correct?

**Comment by schroef** [comment] 2015-04-14 01:34
The same issue occurred on 2 different meshes, so same mesh shape but mirrored and single meshes with mirrored uv shape. One issue was with a part of headlights, the other was with a part of wall.

Just tried splitting the mesh in 2 separating and than transfer UV maps. Even though the mesh is the same this also bugs with the uv layout. Im gonna test earlier version of blender and see what happens. Ill also try 2.74

**Comment by schroef** [comment] 2015-04-14 04:31
I tried 2.74 and doesnt make any difference. Still copies some quads with wrong uv texture. tried modeling the part from scratch which gave sort of the same result. Now im wondering whats going on, perhaps some settings have set wrong??? Tried simpel shape as well, a sphere, gave the same result

**Comment by schroef** [comment] 2015-04-14 04:33
also tried copying exact same mesh, same vertice number. A exact duplicate works, a mesh with same amount of vertices but build different doesnt work.

**Comment by nutti** [comment] 2015-04-14 11:26
Please tell me that you copy/paste between "object" or "mesh".

**Comment by schroef** [comment] 2015-04-14 13:28
Both methods

**Comment by nutti** [comment] 2015-04-16 10:11
Umm... it seems this problem is caused by blender itself, not this addon.

This plugin does not change vertex indices.
Furthermore, I checked vertex indices about meshes, and I found that these indices does not match.

When I fix this problem, I must implement new feature.
New feature must be independent to vertex indices.
But I can not image how to implement this feature now.

**Comment by schroef** [comment] 2015-04-17 18:08
Hmm thats to bad. Not sure why these weird vertice index are happening, i dont know that much about blender. So i cant help you with this. Probable blender uses this index to copy texture over

**Comment by nutti** [comment] 2015-05-03 13:45
I may be come up with this solution.
I tried to implement this one as new feature.

However, I would like to release v3.0 soon.
This feature will be added on v4.0.

**Comment by nutti** [comment] 2015-06-17 09:13
Hi!

Is this problem solved in v3.1 when you use Transfer UV?
This feature supports topology bases copy/paste.

**Comment by schroef** [comment] 2015-06-17 13:28
Not sure how it works but i get this error in 2.74

```Traceback (most recent call last):
  File "/Users/romboutversluijs/Library/Application Support/Blender/2.74/scripts/addons/uv_copy_and_paste_uv/cpuv_transfer_uv_operation.py", line 62, in execute
    for face_data in all_sorted_faces.values():
AttributeError: 'set' object has no attribute 'values'

location: <unknown location>:-1```

**Comment by nutti** [comment] 2015-06-17 13:30
Transfer UV must select 2 face when copy/paste UV.

you can check how to use Transfer UV.

[![](http://img.youtube.com/vi/p1W6jugsyZw/0.jpg)](https://www.youtube.com/watch?v=p1W6jugsyZw)  
[![](http://img.youtube.com/vi/LicrCKTV5kM/0.jpg)](https://www.youtube.com/watch?v=LicrCKTV5kM)

**Comment by mifth** [comment] 2015-06-17 13:33
@schroef give us the test file,  please. And steps to reproduce.

**Comment by schroef** [comment] 2015-06-17 13:54
Doesnt matter i tried on all meshes, also new meshes keeps giving me the same error.

Just to be clear, i select a face in face mode>transfer copy UV....
Than i already get that error

**Comment by nutti** [comment] 2015-06-17 14:13
@schroef 

Do you select **2 faces**?
I have a same error when only 1 face is selected.

I'm also using Blender 2.74.
And it works correctly when select 2 faces.

**Comment by mifth** [comment] 2015-06-17 14:15
I guess there is need a check:
if len(sel_faces) != 2:
 cancel

**Comment by mifth** [comment] 2015-06-17 14:18
I can add it if you want.

**Comment by schroef** [comment] 2015-06-17 14:25
Okay i tried 2 faces now and i dont get the error. It however copy just a small part of the mesh and not all of it

https://www.dropbox.com/s/rlqisvi9b3ymgb4/copy-uv-test.blend?dl=0

**Comment by nutti** [comment] 2015-06-17 14:26
@mifth 

I'm going to revise this just now.
However, you should revise this when you pull req new feature mentioned in #11 .
And I could not understand this condition checking in if-statement.
https://github.com/nutti/Copy-And-Paste-UV/blob/develop/uv_copy_and_paste_uv/cpuv_transfer_uv_operation.py#L127

Is it possible to change below code?
```
if len(sel_faces) != 2 or not (active_face in sel_faces):
```

**Comment by schroef** [comment] 2015-06-17 14:30
Okay tried the monkey again from scratch and works now. Im gonna try my other model now

**Comment by mifth** [comment] 2015-06-17 14:31
@nutti 
Ah, it seems it should be like this:
"if len(sel_faces) != 2 or not active_face or active_face not in sel_faces:"

It should check if we have:
2 selections
 active face
and the active face in the list of selected

I wrote it at night :)

**Comment by nutti** [comment] 2015-06-17 14:31
@schroef 

I'm tried too.
It seems to work correctly.

**Comment by nutti** [comment] 2015-06-17 14:34
@mifth 

Very very thanks!!

> 2 selections
> active face
> and the active face in the list of selected

Aha, I understand that 2nd expression checks bm.faces.active exists or not.

**Comment by mifth** [comment] 2015-06-17 14:35
@nutti 
yep. :)

**Comment by schroef** [comment] 2015-06-17 14:44
Okay the UV transfer works. But i still see mixed faces. Here is the model, you do need to separate the mesh in the middle and than test it. If you look good some indexes are not correct

https://www.dropbox.com/s/rg7qelv4l9n6ogp/UVtest%20wall.blend?dl=0

**Comment by nutti** [comment] 2015-06-17 14:56
I think current version of Transfer UV can't copy/paste UV between part of mesh.
Transfer UV can copy/paste between separated meshes.

I think partial copy/paste UV is needed mentioned below links.
http://blenderartists.org/forum/showthread.php?348421-Addon-Copy-and-Paste-UV-Coordinates&p=2888878&viewfull=1#post2888878

@mifth 
I think copy/paste between partial meshes is needed.
I think this feature is feasible below instruction.
1. select 2 polygons (src)
2. select all polygons (src)
3. select 2 polygons (dest)
4. select all polygons (dest)
What do you think?

**Comment by mifth** [comment] 2015-06-17 15:07
@schroef  in your situation you can split parts and mirror one part to copy.
http://youtu.be/rD7t3P_UiVM

But it's better to use mirror modifier for such models. It will mirror uvs.

**Comment by mifth** [comment] 2015-06-17 15:14
@nutty

I think this situation is incorrect a bit. People should use mirror modifiers for such models.
Modo has no such thing.

**Comment by schroef** [comment] 2015-06-17 15:58
So for all such like models i should use mirror. I just didnt want it to be mirrored, i thought this addon would help here. I didnt mirrored the mesh and than used UV transfer, i separated it with Y (both parts) than used transfer copy and than transfer paste on the other part.

So it more for not symmetrical meshes which have a seam which splits it? Hope you get this explanation

**Comment by mifth** [comment] 2015-06-17 16:17
Yes you can split mesh with Y key and use transfer uv.

Uv transferring happens for all connected edges.

**Comment by schroef** [comment] 2015-06-17 16:42
@mifth 
I tried that but this still gives not correct vertice indexes

**Comment by mifth** [comment] 2015-06-17 16:50
@schroef
then do what i did on the video.
or use mirror modifier.
i don‘t understand your problem.
possibly you go in wrong way.

**Comment by schroef** [comment] 2015-06-17 17:01
i understand that, but i dont want it mirrored like that. I just need to find something else. I need to find different usage for this plugin

**Comment by mifth** [comment] 2015-06-18 08:46
@schroef Then i can't help you in this area.

It's supposed you paste uvs from one mesh to another.
Like this example:
Screen: ![cache0](https://cloud.githubusercontent.com/assets/2251298/7091198/d333a2bc-dfb0-11e4-99f0-6f309d786083.png)

**Comment by nutti** [comment] 2015-06-18 13:11
@schroef 

Sorry, I can't understand your situation well too.
Do you want partially copy/paste in **same** mesh?

**Comment by schroef** [comment] 2015-06-18 13:44
My idea was to paste the same same unwrap on to the other part and than be
able to move it. More sort of a projection or so. With modifier your not
able to unless you make it real mesh afterwards and than move it

Rombout

**Comment by nutti** [comment] 2015-06-18 14:17
@schroef 

Is this problem is related #29 ?
Can you try this one.
Download link is [here](https://github.com/nutti/Copy-And-Paste-UV/archive/develop.zip)
Usage is confirmed in #29 .

**Comment by schroef** [comment] 2015-06-18 14:40
Yes i think that could solve/help me with my case. though the name is a bit
awkward perhaps, isnt partially copy/paste uv visible mesh better than
unhidden mesh?

Rombout

**Comment by mifth** [comment] 2015-06-19 07:31
It does not matter how it's called. :)
The general thing - it works!

Can we close the issue?

**Comment by nutti** [comment] 2015-06-19 12:21
@mifth

ok.
Bug is solved by your great help.
Thank you very much!!

**Closed by nutti** 2015-06-19 12:21 UTC
Labels: Enhancement, Need Collaborator
