### ISSUE TITLE
Transfer UVs Position Feature

### ISSUE THREAD

**Issue by mifth** [nutti/Copy-And-Paste-UV#11] opened 2015-04-10 15:39 UTC
Hi.

I found Modo 901 new feature "Transfer UV positins" using only 2 polygons. I guess they use Increase Selection and check uvs of original and destination meshes.

Here is the video (2:00 minute) https://vimeo.com/124320824

Screen: ![cache0](https://cloud.githubusercontent.com/assets/2251298/7091198/d333a2bc-dfb0-11e4-99f0-6f309d786083.png)

**Comment by nutti** [comment] 2015-04-10 15:42
Wow... it sounds great!
I want to know what algorithm this feature uses.

**Comment by mifth** [comment] 2015-04-10 15:50
I guess we can use "bpy.ops.mesh.select_more()" and compare point oordinated in 3d and point coordinate in 2d somehow.

**Comment by nutti** [comment] 2015-04-28 14:12
Sorry, please give me idea.

I'm developing this feature as "Transfer UV".
However, I can't come up with how to implement this feature.
Currently, I implemented as follows.

1. select "source" object
2. `bpy.ops.mesh.select_more()`
3. select "destination" object
4. `bpy.ops.mesh.select_more()`
5. compare "source" and "destination" faces
6. return to 1. when no more faces are selected

I can't image how to implement 5.
When `bpy.ops.mesh.select_more()` is used, more than 2 faces are selected.
It is not possible what source face is coincidence with destination face.

**Comment by mifth** [comment] 2015-04-28 20:15
Sorry, no free time.
I'll write my idea tomorrow.

**Comment by nutti** [comment] 2015-04-29 01:18
Year, not need to reply hurry.

**Comment by mifth** [comment] 2015-04-29 19:57
Hi! Sorry for late responce. I had some issues on my job.

Here is my idea how it should work.
![cache0](https://cloud.githubusercontent.com/assets/2251298/7400029/a1ae541e-eec2-11e4-84b7-5f85a54f75ad.png)

We copy a mesh in the same way. Looping with GrowSelection operator and check which faces are connected to previous meshes. And check their UVs sure.
Then we paste the Us in the same way. Just select a fase or 2 faces and check compatibility of orginal mesh with the new mesh which we want to paste UVs according to GrowSelection operator too.

That's pretty complex task. But thi is very powerful. As we saw haw it works in Modo.

**Comment by mifth** [comment] 2015-04-29 19:58
What do you think? Is it possible to make?

**Comment by nutti** [comment] 2015-04-30 00:29
Thank you for your reply.

I implemented this process already.
However, I couldn't recoginize newly selected faces when more than two faces are selected by `bpy.ops.mesh.select_more`.

For example, if two faces on source object is selected, which face coincidence with them on destination object.

**Comment by nutti** [comment] 2015-04-30 00:56
Here is an image I'm annoying.

![issue11](https://cloud.githubusercontent.com/assets/1463952/7404528/344f367e-ef1f-11e4-93c5-5ca435c93eed.png)

**Comment by mifth** [comment] 2015-04-30 06:00
I think on the first loop of “select_more“ we will not find which face is topology based to the source. we need to loop entire selected faces and gather information about all faces and verts. 
for example if on rhe third or fourth loop topology will be unique like - we can find which face belongs to the source.
i‘ll write more soon. this is really interesting feature.

**Comment by mifth** [comment] 2015-04-30 06:03
Just try to select_more 3 or 4 times. i‘m sure you will see unique like topology.
and then we can get shared verts of faces to understand the topology.

what do you think about this way?

**Comment by nutti** [comment] 2015-04-30 06:51
Thanks, I understood your idea.
May be this method works fine.

But is there any method that selected shapes are same between source and destination?

**Comment by mifth** [comment] 2015-04-30 07:34
I think blender is limited in this area. We have to find our own methods.

**Comment by nutti** [comment] 2015-04-30 16:19
May be I did it!!
Please confirm new add-on.
https://github.com/nutti/Copy-And-Paste-UV/tree/develop

Tutorial: https://www.youtube.com/watch?v=rbP0hExl3Zc
(Upload is processing. please wait...)

And I released version 3.0-beta-1.
I will be released rc version when #14 is closed.

**Comment by mifth** [comment] 2015-04-30 19:22
Hello! Great attempt!

I tested 2 cubes. One cube i subdivided and another cube i did with LoopCuts. UVs Transfering was not made. Sorry. :(

Here is my test: http://youtu.be/zBDr8YSNW4s

**Comment by mifth** [comment] 2015-04-30 19:26
Question: why do you go in edit mode into original object?
You can just copy information(UVs indices, points, custom calculations and checks of selections etc.) into array and there will not be a need in original object at all.

**Comment by mifth** [comment] 2015-04-30 19:43
Hey!
It seems I understand why Modo selects 2 faces to transfer uvs. Here is the logic:
![cache0](https://cloud.githubusercontent.com/assets/2251298/7421022/00b74d54-ef8a-11e4-9550-4d5828cd206f.png)

We have 2 selected faces. One of them is Active. And we can get Active side and Inactive side.
Then we loop for select_more and gather information about faces, verts, uvs.
In this way we ca copy and then paste uvs.

What do you think?

**Comment by mifth** [comment] 2015-04-30 19:47
it's not so simple as we can have different topology and triangles/ngons.
But this is very cool feature.

Also i think you don't need to go in edit mode into origial object during the Paste operation. You need to gather information into dict/array during Copying operation only.

**Comment by nutti** [comment] 2015-05-01 00:46
> One cube i subdivided and another cube i did with LoopCuts. UVs Transfering was not made.
Umm... this needs to be fixed.

> Question: why do you go in edit mode into original object?
> Also i think you don't need to go in edit mode into origial object during the Paste operation. You need to gather information into dict/array during Copying operation only.
Please tell me where?
Some operation (i.e. `bpy.ops.mesh.select_more`) must be object/edit mode.

> We have 2 selected faces. One of them is Active. And we can get Active side and Inactive side.
> Then we loop for select_more and gather information about faces, verts, uvs.
> In this way we ca copy and then paste uvs.
I can not understand why we should divide "Active" and "Inactive" side.
It seems that only active face works fine.

> it's not so simple as we can have different topology and triangles/ngons.
I think so.
If we take topology/triangles/ngons into account, we must improve this add-on.

**Comment by nutti** [comment] 2015-05-02 06:38
> One cube i subdivided and another cube i did with LoopCuts. UVs Transfering was not made.

I fixed this one.
Algorithm is incorrect in previous version.
https://github.com/nutti/Copy-And-Paste-UV/tree/develop

**Comment by mifth** [comment] 2015-05-02 07:51
Great! Let me test again. i‘ll be on computer in 2-3 hours.

i also have idea how to find front and back side. we need only one face and one active edge. i‘llwrite soon.

**Comment by mifth** [comment] 2015-05-02 09:49
I tested!
Works great with quads!

Found 2 issues:
https://youtu.be/-vfyaozlVJM - if 2 parts in one mesh. it does not work.
https://youtu.be/gfS30eRFYzA - if i triangulate one quad - exception will be. I hope ngons and triangles can be supported.

**Comment by nutti** [comment] 2015-05-02 15:22
> if 2 parts in one mesh. it does not work.
> if i triangulate one quad - exception will be. I hope ngons and triangles can be supported.

I'll fixed these bugs.
https://github.com/nutti/Copy-And-Paste-UV/tree/develop

Former problem must be solved more gracefully.
I'll fix this problem soon.
Temporary, you can select strategy on ToolShelf.

Later problem is caused by output debugging string.
I forgot to delete this one.

**Comment by nutti** [comment] 2015-05-03 13:19
I finished fix this problem.
Please confirm new version.
https://github.com/nutti/Copy-And-Paste-UV/tree/develop

And, It's about time to publish version 3.0-rc to use this feature more and more people.
If you have no big problem, I'll publish version 3.0-rc.
What do you think?

**Comment by zeauro** [comment] 2015-05-03 16:09
![uv_transfer](https://cloud.githubusercontent.com/assets/8408853/7445728/517c9262-f1bf-11e4-8e27-c1e9207aec4e.png)
UV Transfer does not work for me. I only obtained one face wrongly unwrap and all edges selected.

**Comment by nutti** [comment] 2015-05-03 23:55
@zeauro 
Please confirm to fix the problem when you change "strategy" on ToolShelf option.
We must change transfer strategy when topology is changed.

**Comment by nutti** [comment] 2015-05-04 06:56
I made a picture.
You can change strategy indicated red rectangle.

![20150504](https://cloud.githubusercontent.com/assets/1463952/7449646/dfb0f774-f275-11e4-991a-9fd490a8419c.png)

**Comment by zeauro** [comment] 2015-05-04 09:26
No. Problem is the same if I change strategy.
I can increase precision slider. More faces are unwrapped at correct scale but no all and it does not give expected result. Some gaps are appearing between faces.
I don't have these problems with spheres. But UV transfer also fails with torus.

**Comment by nutti** [comment] 2015-05-04 12:47
@zeauro 
It seems work correctly in my environment.

[![](http://img.youtube.com/vi/p1W6jugsyZw/0.jpg)](https://www.youtube.com/watch?v=p1W6jugsyZw)

**Comment by mifth** [comment] 2015-05-04 15:29
Hi.
i‘ll test soon. please don‘t close the issue yet.

**Comment by mifth** [comment] 2015-05-04 18:59
Hi.

I found that it does not work for modified mesh. The same thing as @zeauro found. I just scaled and rotated mesh a bit.
I think you found not the best topology approach. It needs refactoring.

![cache0](https://cloud.githubusercontent.com/assets/2251298/7460007/b33cd13a-f2a8-11e4-8622-cd1cb4e5c051.png)

**Comment by nutti** [comment] 2015-05-05 00:41
> i‘ll test soon. please don‘t close the issue yet.

Yes, of course. I will close issue when this problem is solved.

This problem is caused by algorithm to check same face by center/normal of face, and will be fixed when adapts index matching algorithm.
What do you think?

**Comment by nutti** [comment] 2015-05-05 06:37
Hmm, I have no idea to identify same faces when objects are copied in 'edit mode'.
In edit mode, position/normal are changed when change scale or rotation.
I think this problem is same as issue #6.

I will tackle new feature "Copy/Paste UV by topology" in version 4.0.
This feature will solve these problem, however I have no idea now.

**Comment by nutti** [comment] 2015-05-05 15:54
> This problem is caused by algorithm to check same face by center/normal of face, and will be fixed when adapts index matching algorithm.

Hmm..., This approach makes the problem worse.
Particularly, copying mesh in **edit mode**.
In this case, there are no faces to match index between source and destination.

@mifth, @zeauro 
Unfortunately, scaling/rotation in "edit mode" makes mesh's topology (in Blender) change.
Until now, I only thought that scaling/rotation about meshes in Blender is performed on **object mode**.
So, I want to support topological copying as a new feature #18 because algorithm will be almost different from current one. 
What do you think?

**Comment by nutti** [comment] 2015-05-07 14:31
I have a question.

Is there any method to revert mesh before transformation in blender?
For example, when mesh(all vertices) is rotated in "edit mode", can we get rotation angle?
If this problem is solved, I can try new strategy.

**Comment by nutti** [comment] 2015-05-07 15:21
@mifth 
Ahh..., I thought this problem more difficult !
I should implement only this one ....

> We have 2 selected faces. One of them is Active. And we can get Active side and Inactive side.
Then we loop for select_more and gather information about faces, verts, uvs.
In this way we ca copy and then paste uvs.

I only have to get selected polygon indices and copy/paste between source and destination.
Topology matching makes me confused. This process may not be needed in this feature.
I can do it soon!

By the way, Modo 901 seems not to use "topology matching".
I think that "Transfer UVs" is failed when index ordering was changed.
What do you think about Modo 901's feature "Transfer UVs"?

**Comment by mifth** [comment] 2015-05-07 15:59
Hi.
I‘m on vacation right now. sorry i‘m not so active these days.

i dunno know about modo. but i‘m sure they use topology matching. they even have topology mirror selection which is introduced in the video(check it).

I‘ll try to make another concept when i‘ll be computer.

**Comment by nutti** [comment] 2015-05-08 13:24
@mifth, @zeauro 
I simplify "Transfer UV" algorithm.
Please try newest version.
https://github.com/nutti/Copy-And-Paste-UV/tree/develop

If mesh is rotated/scaled, transferring UV works correctly.

**Comment by mifth** [comment] 2015-05-09 14:03
Hello!

Sorry for late responce. I tested. Some uvs are not transfered correctly. Here is my simple test:
https://youtu.be/0FGQWoSlrPw

**Comment by nutti** [comment] 2015-05-09 15:24
I checked modo 901 tutorial video again, and I thought that **Transfer UV** can be succeeded when  few topology is changed.

So far, I tried 3 method to match topology.
I think there is no solution to solve problem as follows.
Do you have any other solutions?

|Strategy|Problem|
|---|---|
|Face Index|Similar object but making process is different|
|Face position(center)|Edit mesh in **Edit mode**|
|Face normal|Cube shape. Edit mesh in **Edit mode**| 

@mifth 
I want to ask you.
You should be a collaborator because you support this add-on when I pushed this add-on to blender's master repository.
If you are not problem, I want to add you this project as a collaborator.
Is it OK?

**Comment by mifth** [comment] 2015-05-10 19:40
Hi.

About strategy i think like this:
Faces which have the same vertices indeces and the same edges. I mean this:
![cache0](https://cloud.githubusercontent.com/assets/2251298/7555932/59565990-f765-11e4-967d-a4d197df92a2.png)

Sure i'll try to help you. But right now i'm busy with MiraTools which i've been developing. http://blenderartists.org/forum/showthread.php?366107-MiraTools I'll finish them in a month.

**Comment by nutti** [comment] 2015-05-11 14:17
Please tell me about your strategy.
I want to know How to judge whether topology is same or not.
If mesh's vertex index is changed, this method will be failed because bm.face.verts/edges can only get index.

> Sure i'll try to help you. But right now i'm busy with MiraTools which i've been developing. 
Thanks!
Until you are free, I tackle this problem.

**Comment by nutti** [comment] 2015-05-19 14:34
Someone needs new version v3.0.
So, I change milestone from **Version 3.0** to **TBD** because I can not suppose finish date.
I keep this issue opened and I will continue improving this feature.

Sorry.

**Comment by mifth** [comment] 2015-05-19 14:36
Yes sure. Just keep it open.

**Comment by mifth** [comment] 2015-06-11 19:53
Hi. I'm gonna rewrite Toplogy copy/paste.
Should I create a new file or i can replace Transfer file?

**Comment by nutti** [comment] 2015-06-11 20:30
Hi,

Yes, you can pull req your sources to develop branch.
However, your source will be merged in v3.1 or v4.0 because v3.0 sources are in review #25.

**Comment by nutti** [comment] 2015-06-12 12:49
Ah... I didn't understand your comment.

> Should I create a new file or i can replace Transfer file?

Yes, you can create new file or replace transfer file you like.
I think that you can easily add your feature if you create new file.

**Comment by mifth** [comment] 2015-06-13 13:37
Hi.
I forked the dev banch and created a new file. I have slow progress but i have good direction what i should do.
that‘s really not so simple task.

**Comment by nutti** [comment] 2015-06-13 13:53
@mifth 
Thanks for tackling this issue!!
I think this task is not simple too.
However, this feature makes this add-on more powerful.

**Comment by mifth** [comment] 2015-06-15 07:38
Hi. i have good progress. i almost finished this feature. almost everything works like in modo 901.
i need to fix one thing and i‘ll write you here to check the code.
i did everything in bmesh. bmesh is really powerful.

**Comment by nutti** [comment] 2015-06-15 10:20
@mifth

Great news!!
If you don't mind, please tell me your algorithm.

**Comment by mifth** [comment] 2015-06-15 20:55
@nutti I finished first version of topology copy/paste.

Here is my video test: http://youtu.be/LicrCKTV5kM

Here is 300 lines of code:
https://github.com/mifth/Copy-And-Paste-UV-mifth
https://github.com/mifth/Copy-And-Paste-UV-mifth/blob/topology/uv_copy_and_paste_uv/cpuv_topology.py

the algorithm has become very simple:
1) select 2 faces
2) find shared edge between faces
3) get the first point using cross and dot calculation of the shared edge
4) sort all edges and all verts of the selected faces
5) parse every edge of the faces to get connected new faces.
6) parse new connected faces in the same way

This code works through all objects. I can copy uvs from one object and paste into other object at any active uvLayer. As I use Global array of copied uv coordinates.

Also BMesh has good methods here:
http://www.blender.org/api/blender_python_api_2_74_5/bmesh.types.html
Check BMVert/BMEdge/BMFace classes
I like methods like:
edge.calc_length()
edge.other_vert(vert)
face.calc_center_median()
face.loops

Also, you can refactor other copy/paste tools so that use only EditMode and Global array of vectors.

I'm ready to make Pull request if you don't mind. :)

**Comment by mifth** [comment] 2015-06-15 21:29
Also this method has some limitations:
Edge must share only 2 faces.

Such a mesh will be incorrect for the feature:
![image](https://cloud.githubusercontent.com/assets/2251298/8171179/b52b891e-13be-11e5-98c9-d74c7b1aa1dd.png)

**Comment by nutti** [comment] 2015-06-15 23:11
Great!

You can pull req to develop branch now.
I would like to review your code.
And this feature will be included in v3.1.

Then, I have a question about your algorithm.
I think you sort faces in your algorithm.
What is sort algorithm you use?
I'm very interested in sort algorithm because I could not recoginize growing faces.

**Comment by nutti** [comment] 2015-06-15 23:19
I think that current Transfer UV feature will not be used.

I want to include your feature as Transfer UV.
 What do you think?

**Comment by mifth** [comment] 2015-06-16 08:58
Ok, I did Pull request and put the code into Transfer UV feature.

Here is my algorithm:
1) we find shared edge
https://github.com/mifth/Copy-And-Paste-UV-mifth/blob/c09ee5643afbc1e101658c8b1c5343154b818144/uv_copy_and_paste_uv/cpuv_transfer_uv_operation.py#L143-L150
![cache0](https://cloud.githubusercontent.com/assets/2251298/8179217/e64025a0-141d-11e5-9b25-b1da5684e404.png)

2) we sort verts using some simple vector math to check some angles
https://github.com/mifth/Copy-And-Paste-UV-mifth/blob/c09ee5643afbc1e101658c8b1c5343154b818144/uv_copy_and_paste_uv/cpuv_transfer_uv_operation.py#L151-L169
![cache1](https://cloud.githubusercontent.com/assets/2251298/8179268/32637f04-141e-11e5-8041-93067c566120.png)
![cache2](https://cloud.githubusercontent.com/assets/2251298/8179272/35857070-141e-11e5-843b-2f3dcaaf94b0.png)

3)Then if we have 2 sorted verts and the edge - we can sort other verts of the faces
https://github.com/mifth/Copy-And-Paste-UV-mifth/blob/c09ee5643afbc1e101658c8b1c5343154b818144/uv_copy_and_paste_uv/cpuv_transfer_uv_operation.py#L172
https://github.com/mifth/Copy-And-Paste-UV-mifth/blob/c09ee5643afbc1e101658c8b1c5343154b818144/uv_copy_and_paste_uv/cpuv_transfer_uv_operation.py#L288-L320
![cache3](https://cloud.githubusercontent.com/assets/2251298/8179302/7a4bcbdc-141e-11e5-9c41-b202a8d34d28.png)

4) Then we parse other faces which are linked to edges
https://github.com/mifth/Copy-And-Paste-UV-mifth/blob/c09ee5643afbc1e101658c8b1c5343154b818144/uv_copy_and_paste_uv/cpuv_transfer_uv_operation.py#L195-L212
![cache4](https://cloud.githubusercontent.com/assets/2251298/8179349/b666504c-141e-11e5-8e83-a5292f2e6f3a.png)
![cache5](https://cloud.githubusercontent.com/assets/2251298/8179352/b974d416-141e-11e5-8251-b78bc4ab51da.png)

5) then we copy uv vectors and uv_pins into array
https://github.com/mifth/Copy-And-Paste-UV-mifth/blob/c09ee5643afbc1e101658c8b1c5343154b818144/uv_copy_and_paste_uv/cpuv_transfer_uv_operation.py#L65-L74

Paste works in the same way. The only difference is we paste the array of uvs.
https://github.com/mifth/Copy-And-Paste-UV-mifth/blob/c09ee5643afbc1e101658c8b1c5343154b818144/uv_copy_and_paste_uv/cpuv_transfer_uv_operation.py#L102-L123

**Comment by nutti** [comment] 2015-06-16 09:16
Very very cool job!!

I'm going to review your code.

However, I have a suggestion about your pull request.
Your pull request is consists of many commits. (ex. wip commits.)

So, please make only one commit.
Here is instruction:

+ `git checkout topology`
+ `git checkout -b feature`
+ `git rebase -i develop`
+ (Will open texteditor) Rewrite `pick` to `squash` without head line of file
+ Save and close it
+ (Will open texteditor again) Write new commit measage
+ Save and close it
+ `git push origin feature`
+ Pull request from `feature` branch

If this instruction is made, your commit will become very clean state.

Sorry, for inconvenience.

**Comment by nutti** [comment] 2015-06-16 09:31
I will try another method if you can't work this instruction :-)

**Comment by mifth** [comment] 2015-06-16 10:02
I'm not good in pull requests.
Check this request https://github.com/nutti/Copy-And-Paste-UV/pull/27

**Comment by nutti** [comment] 2015-06-16 10:09
Great! Thanks you!!

I can review your code more easily!!

Please wait for my review.

**Comment by nutti** [comment] 2015-06-16 10:38
Sorry, I pause review for one hour.

**Comment by nutti** [comment] 2015-06-16 13:57
@mifth 
Your coding is great.
It was very useful for me to understand python and blender API more :-)

Finally, please tell me your algorithm.

> 2) we sort verts using some simple vector math to check some angles

Is this sorting algorithm depended on bmesh?

**Comment by mifth** [comment] 2015-06-16 14:05
Thanks. :)

"2)" is only for selected 2 faces. To get shared edge and sort first two verts.
All other sorting has no vector math.

Most stuff can be done without bmesh i think. But bmesh has good functions like:
edge.link_faces
edge.other_vert(vert)

**Comment by nutti** [comment] 2015-06-16 14:17
Yeah, thank you!

I will merge your source code, then I made small change about your patch mentioned in review.
After that, I will release v3.1.

**Comment by mifth** [comment] 2015-06-16 14:26
That's great! :)
Thank you too!

**Comment by nutti** [comment] 2015-06-16 15:24
Released v3.1!!
Thanks for your contribution.

However, your contribution on [cpuv_transfer_uv.py](https://github.com/nutti/Copy-And-Paste-UV/blob/master/uv_copy_and_paste_uv/cpuv_transfer_uv_operation.py) is disappeared, and I don't know why.
Sorry...

**Comment by mifth** [comment] 2015-06-16 15:50
Great!
No problem. It's ok if it works.

Btw, why do you need this class? https://github.com/nutti/Copy-And-Paste-UV/blob/master/uv_copy_and_paste_uv/cpuv_transfer_uv_operation.py#L33-L38

If "cpuv_properties.topology_copied" is copied - a user can paste into any object already.

**Comment by mifth** [comment] 2015-06-16 19:10
@nutti I was wrong!

Your script does not store data in blend file. As you did not used Properies. You just named variables.
You went in right direction with "bpy.types.Scene".

Blender store data only if we use properties CollectionProperty/BoolPproperty/FloatProperty/IntProperty classes from here http://www.blender.org/api/blender_python_api_2_74_5/bpy.props.html?highlight=collectionproperty#bpy.props.CollectionProperty

If you set only sarray or Boolean or String - it will not be stored in blend file.

Sorry i was wrong. You can revert that part.

**Comment by nutti** [comment] 2015-06-17 12:49
@mifth 

Hi,

> Btw, why do you need this class? https://github.com/nutti/Copy-And-Paste-UV/blob/master/uv_copy_and_paste_uv/cpuv_transfer_uv_operation.py#L33-L38

Oh..., I can't notice that this class is not used in this file on review.
I deleted it.

> Your script does not store data in blend file. As you did not used Properies. You just named variables.
> You went in right direction with "bpy.types.Scene".

Thanks for your investigation.
I revised it.
Please check current version.

**Comment by mifth** [comment] 2015-06-17 13:14
Hi!

I have just tested. All works good! Gread job.

I would like to make another small improvent to paste into many objects at the same time. I'll make another pull request in 4-5 hours if you don't mind.

**Comment by nutti** [comment] 2015-06-17 13:16
Thanks

> I would like to make another small improvent to paste into many objects at the same time. I'll make another pull request in 4-5 hours if you don't mind.

Is this related to #23 ?
or, new feature?

**Comment by mifth** [comment] 2015-06-17 13:21
Possibly. I dunno know what is N to M?

It's related to Modo's feature. As they can copy to many objects at once.
https://cloud.githubusercontent.com/assets/2251298/7091198/d333a2bc-dfb0-11e4-99f0-6f309d786083.png

I'll try to add your bmesh history to paste code.

**Comment by nutti** [comment] 2015-06-17 13:28
Ah... this is not same as #23 .
#23 is N **polygon to M **polygon** not object.
I'll try to develop this #23 .

> It's related to Modo's feature. As they can copy to many objects at once.
> https://cloud.githubusercontent.com/assets/2251298/7091198/d333a2bc-dfb0-11e4-99f0-6f309d786083.png

This is great feature.
If you don't mind, can you implement this feature?

I think another feature should support this feature.
Maybe, this is my homework

**Comment by mifth** [comment] 2015-06-17 13:32
I'll implement it soon sure.
In 4-5 hours.

**Comment by mifth** [comment] 2015-06-17 20:39
Hi.

I added multiple UVS paste.

Here is the pull request: https://github.com/nutti/Copy-And-Paste-UV/pull/28
Here is video test: http://youtu.be/ddq1J_y1RMc

**Comment by nutti** [comment] 2015-06-18 10:08
Great job!!

I will review.
I'm outside now, please wait.

**Comment by mifth** [comment] 2015-06-18 10:11
Sure.

**Comment by nutti** [comment] 2015-06-18 12:36
@mifth 

Sorry, I'm late...
I reviewed your pull request.

**Comment by nutti** [comment] 2015-06-18 13:30
@mifth 
Great patch!!
Please answer last question about [this](https://github.com/nutti/Copy-And-Paste-UV/pull/28/files#diff-89d3560a569a37db3092b52bfd87340dR104)

**Comment by nutti** [comment] 2015-06-18 13:54
@mifth 

Thanks!!
I merged your pull request and refactored code mentioned #28 .

And I have a suggestion about this issue.
Transfer UV task may be over for your great help.
Is it possible to close issue?

**Comment by mifth** [comment] 2015-06-18 14:04
Yes. It's come to conclusion. We did it like in Modo! And even better. :)

**Comment by nutti** [comment] 2015-06-18 14:06
@mifth 

Very very good contribution you are!!!
Thank you very much.

When you want to improve this feature, you can make new issue :-)

**Closed** 2015-06-18 14:06 UTC
Labels: Enhancement
